version: "3"
services:

  mysql-db:
    image: mysql
    restart: always
    container_name: firstproj-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    links:
      - mysql-db

  firstproject:
    build:
      context: ./
      dockerfile: Dockerfile
    image: firstproject:lrv
    container_name: firstproj
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www
    links:
      - mysql-db
    ports:
      - 8000:8000
    command:
      php artisan serve --port=8000 --host=0.0.0.0

volumes:
  database:
    external: true
