version: "3"
services:

  mysql-db:
    image: mysql
    restart: always
    container_name: firstproj-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: firstproj-adm
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    links:
      - mysql-db

  firstproject:
    build:
      context: ./
      dockerfile: Dockerfile
    image: firstproject:lrv
    container_name: firstproj
    tty: true
    working_dir: /var/www/
    volumes:
      - .:/var/www
    links:
      - mysql-db
      - nginx
    ports:
      - 8000:8000
  
  nginx:
    image: nginx
    container_name: firstproj-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  database:
    external: true
